### ISSUE TITLE
No package compatible with h5py 3.9 and python 3.11

### ISSUE THREAD

**Issue by bhazelton** [conda-forge/python-casacore-feedstock#32]
### Comment:

I'm not quite sure why there's a conflict, but I cannot get conda (or mamba) to resolve an environment on python 3.11 with h5py>=3.9 and python-casacore>=3.3.1. This is an issue because numpy 1.25 added a bunch of deprecation warnings that are fixed in h5py 3.9.

Here are the contents of a a minimal environment file that fails to build on Mac (and I believe on Linux as well):

```
name: test_311
channels:
  - conda-forge
dependencies:
  - h5py>=3.9
  - python-casacore>=3.3.1
  - pip
  - python>=3.11
```

And here is the error message when trying to create this env on Mac:

```
Looking for: ["h5py[version='>=3.9']", "python-casacore[version='>=3.3.1']", 'pip', "python[version='>=3.11']"]

Encountered problems while solving:
  - package h5py-3.9.0-mpi_mpich_py38hedc0cae_0 requires python_abi 3.8.* *_cp38, but none of the providers can be installed
```

**Comment by pkgw** [comment]
OK, it looks like the underlying `casacore` package has lost its Python 3.11 builds in the bot-generated updates, so the only available versions have dependencies on older versions of some of the other libraries (namely `hdf5`). I'll try to bring the Python 3.11 builds back.

**Comment by pkgw** [comment]
OK, I am pretty sure that the issue was just that I forgot to add the migration file in my PR that manually added the 3.11 builds. The new PR autolinked above should fix that, I think.

**Comment by bhazelton** [comment]
Great, thanks!

**Comment by pkgw** [comment]
After merging the above, I believe that this issue is fixed. Is that what you're seeing too? If so, please go ahead and close.

**Comment by bhazelton** [comment]
Yes, it seems to be working well. Thank you!!
