### ISSUE TITLE
python-casacore 3.6.1

### ISSUE THREAD

**Issue by Jan-Willem** [conda-forge/python-casacore-feedstock#42]
### Comment:

There are a couple of bug fixes in python-casacore 3.6.1 (released today) that we are interested in. Is there a timeline for releasing this feedstock with python-casacore 3.6.1?

**Comment by ludwigschwardt** [comment]
conda-forge/casacore-feedstock#94 should make you happy :-)

**Comment by pkgw** [comment]
I've merged https://github.com/conda-forge/casacore-feedstock/pull/94 , which updates the underlying C++ libraries. I'm not sure why the robot hasn't yet filed a pull request to update this feedstock, with the Python bindings, but we should be clear to update this package today — it'll take an hour or two for the `casacore` update to propagate through the ecosystem. If the bot doesn't create an update, it's easy to submit one manually instead.

**Comment by pkgw** [comment]
Ah, the conda-forge package isn't updating because the 3.6.1 release of python-casacore doesn't include a source package:

https://pypi.org/project/python-casacore/#files

We need one to produce a new build, unless the recommendation is to start building packages based on GitHub Release archives.

**Comment by Jan-Willem** [comment]
@pkgw it has now been uploaded.

**Comment by tammojan** [comment]
Oops! All the wheel building magic did not build a source release (which should have been the easy part). For now, I uploaded a source release from the release manually, see https://pypi.org/project/python-casacore/

**Comment by pkgw** [comment]
Candidate update in #43. Note that I needed to tweak our URLs slightly because the current release files are under `python_casacore`, not `python-casacore`; pip treats the names as equivalent but the file URLs are different. It's an easy change for us to make, but something to be aware of.

**Comment by pkgw** [comment]
Solved in #43. It should take a few hours for the update to propagate out into the ecosystem.
